CC=cc
CFLAGS=-Wall
GLIB_CFLAGS=$(shell pkg-config --cflags glib-2.0)


BINS=libruuvitag.so testlistener

all: $(BINS)

libruuvitag.so: libruuvitag.c libruuvitag.h
	$(CC) $(CFLAGS) $(GLIB_CFLAGS) -fPIC -shared -o $@ libruuvitag.c -lc

testlistener: testlistener.c libruuvitag.so
	$(CC) $(CFLAGS) -o $@ testlistener.c -L. -I. -lruuvitag

run: testlistener
	@LD_LIBRARY_PATH="$LD_LIBRARY_PATH;." ./testlistener

clean:
	rm -f *.o $(BINS)
